import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {/* Gradient lines — behind all content */}
        <div className="fixed inset-0 pointer-events-none z-50">
          <div className="gradient-line"></div>
          <div className="gradient-line"></div>
          <div className="gradient-line"></div>
        </div>

        {/* Actual UI */}
        <Header />
        <div className="relative z-10">{children}</div>
        <Footer />
      </body>
    </html>
  );
}